from flask import request, jsonify
from flask_cors import cross_origin
import logging
import re
from typing import Dict, Optional, Tuple, Any
from datetime import datetime
from . import powerbi_docs_bp
from app.auth2.middleware import auth_required, get_current_user_from_token
from app.powerbi_docs.powerbi_service_pbix import PowerBIPbixService
from app.powerbi_docs.ai_client import ai_client
from app.powerbi_docs.services.token_tracking_service import powerbi_docs_token_tracking_service
from app.powerbi_docs.services.generated_docs_service import generated_docs_service
from app.powerbi_docs.services.diagnostics_kpi_service import diagnostics_kpi_service
from app.core.responses import error_response
from app.core.database import get_db_cursor
from app.powerbi_chat.services.vector_store_service import vector_store_service

# Initialize the service with the proper AI client instance
powerbi_docs_service = PowerBIPbixService(ai_client)

# Configure logger
logger = logging.getLogger(__name__)

# Allowed section types
ALLOWED_SECTIONS = {
    'executive_summary',
    'data_model_analysis',
    'visualization_analysis',
    'security_analysis',
    'improvement_recommendations'
}

def _validate_collection_name(collection_name: str) -> bool:
    """
    Validate and sanitize collection_name to prevent SQL injection and path traversal.
    
    Collection names should be alphanumeric with underscores and hyphens only,
    matching the pattern used by vector_store_service (pbix_ prefix + hex UUID).
    
    Args:
        collection_name: The collection name to validate
        
    Returns:
        bool: True if valid, False otherwise
    """
    if not collection_name or not isinstance(collection_name, str):
        return False
    
    # Collection names should match pattern: pbix_ followed by hex characters
    # This matches the pattern generated by vector_store_service.generate_collection_name()
    pattern = r'^pbix_[a-f0-9]{32}$'
    return bool(re.match(pattern, collection_name))

def _get_summaries_by_collection(collection_name: str) -> Tuple[Optional[Dict], Optional[str], Optional[datetime]]:
    """
    Helper function to get summaries from database by collection name.
    
    Returns:
        tuple: (summaries_dict, filename, upload_time) or (None, None, None) if not found
    """
    try:
        with get_db_cursor(commit=False) as cursor:
            cursor.execute("""
                SELECT semantic_model_summary, power_query_summary, visuals_summary, rls_summary, filename, upload_time
                FROM powerbi_file_summaries 
                WHERE collection_name = %s
            """, (collection_name,))
            
            result = cursor.fetchone()
            
            if not result:
                return None, None, None
            
            semantic_model_summary, power_query_summary, visuals_summary, rls_summary, filename, upload_time = result
            
            summaries = {
                'semantic_model_summary': semantic_model_summary,
                'power_query_summary': power_query_summary,
                'visuals_summary': visuals_summary,
                'rls_summary': rls_summary or {}
            }
            
            return summaries, filename, upload_time
                
    except Exception as e:
        logger.error(f"Error retrieving summaries for {collection_name}: {e}", exc_info=True)
        raise


@powerbi_docs_bp.route('/api/powerbi-docs/list-files', methods=['GET'])
@cross_origin(supports_credentials=True)
@auth_required
def list_uploaded_files():
    """
    Endpoint to list all uploaded Power BI files.
    Returns the same format as the chat service.
    """
    try:
        uploaded_files = vector_store_service.list_collections_with_details()
        return jsonify({
            'files': uploaded_files,
            'total_count': len(uploaded_files),
            'status': 'success'
        })
    except Exception as e:
        logger.error(f"Error retrieving list of uploaded files: {e}", exc_info=True)
        return error_response(500, 'Failed to retrieve uploaded files.')

@powerbi_docs_bp.route('/api/powerbi-docs/get-summaries/<collection_name>', methods=['GET'])
@cross_origin(supports_credentials=True)
@auth_required
def get_file_summaries(collection_name):
    """
    Endpoint to get summaries for a specific collection.
    """
    try:
        # Validate collection_name
        if not _validate_collection_name(collection_name):
            return error_response(400, 'Invalid collection name format')
        
        summaries, filename, upload_time = _get_summaries_by_collection(collection_name)
        
        if not summaries:
            return error_response(404, 'File summaries not found')
        
        return jsonify({
            'collection_name': collection_name,
            'filename': filename,
            'upload_time': upload_time.isoformat() if upload_time else None,
            'summaries': summaries,
            'status': 'success'
        })

    except Exception as e:
        logger.error(f"Error retrieving summaries for {collection_name}: {e}", exc_info=True)
        return error_response(500, 'Failed to retrieve file summaries.')

@powerbi_docs_bp.route('/api/powerbi-docs/get-generated-docs/<collection_name>', methods=['GET'])
@cross_origin(supports_credentials=True)
@auth_required
def get_generated_docs(collection_name):
    """
    Endpoint to get all previously generated documentation sections for a collection.
    """
    try:
        # Validate collection_name
        if not _validate_collection_name(collection_name):
            return error_response(400, 'Invalid collection name format')
        
        generated_sections = generated_docs_service.get_all_generated_sections(collection_name)
        
        return jsonify({
            'collection_name': collection_name,
            'generated_sections': generated_sections,
            'status': 'success'
        })

    except Exception as e:
        logger.error(f"Error retrieving generated docs for {collection_name}: {e}", exc_info=True)
        return error_response(500, 'Failed to retrieve generated documentation.')


@powerbi_docs_bp.route('/api/powerbi-docs/analyze-section/<section>', methods=['POST'])
@cross_origin(supports_credentials=True)
@auth_required
def analyze_pbix_section_route(section):
    """
    Endpoint to analyze a specific section using file summaries.
    Expects JSON data with 'collection_name' and optional 'custom_instructions'.
    """
    try:
        # Validate section parameter
        if section not in ALLOWED_SECTIONS:
            return error_response(400, f'Invalid section. Allowed sections: {", ".join(sorted(ALLOWED_SECTIONS))}')
        
        data = request.get_json()
        if not data:
            return error_response(400, 'JSON data is required')
            
        collection_name = data.get('collection_name')
        if not collection_name:
            return error_response(400, 'collection_name is required')
        
        # Validate collection_name
        if not _validate_collection_name(collection_name):
            return error_response(400, 'Invalid collection name format')
            
        custom_instructions = data.get('custom_instructions', '')
        if not isinstance(custom_instructions, str):
            custom_instructions = ''

        # Get summaries from database using helper
        summaries, filename, _ = _get_summaries_by_collection(collection_name)
        
        if not summaries:
            return error_response(404, 'File summaries not found')

        # Analyze the specific section using summaries
        section_analysis, token_usage = powerbi_docs_service.analyze_from_summaries(
            summaries, 
            section, 
            custom_instructions
        )
        
        # Log content length before saving
        analysis_length = len(str(section_analysis)) if section_analysis else 0
        logger.info(f"Section analysis complete for {section} - Length: {analysis_length} chars, preparing to save")
        
        # Save generated content to database with graceful error handling
        try:
            generated_docs_service.save_generated_section(
                collection_name,
                section,
                section_analysis
            )
        except Exception as save_error:
            # Log error but don't fail document generation
            logger.error(f"Failed to save generated section {section}: {save_error}", exc_info=True)
        
        # Record token usage with graceful error handling
        try:
            user = get_current_user_from_token()
            if user and isinstance(user, dict) and user.get('ms_object_id'):
                powerbi_docs_token_tracking_service.record_token_usage(
                    user['ms_object_id'],
                    collection_name,
                    section,
                    token_usage.get('input_tokens', 0),
                    token_usage.get('output_tokens', 0)
                )
        except Exception as tracking_error:
            # Log error but don't fail document generation
            logger.error(f"Failed to record token usage for section {section}: {tracking_error}", exc_info=True)
        
        return jsonify({
            'section': section,
            'analysis': section_analysis,
            'custom_instructions': custom_instructions,
            'filename': filename,
            'token_usage': token_usage
        })

    except Exception as e:
        logger.error(f"Error analyzing section {section}: {e}", exc_info=True)
        return error_response(500, 'Failed to analyze section')

@powerbi_docs_bp.route('/api/powerbi-docs/parse-recommendations', methods=['POST'])
@cross_origin(supports_credentials=True)
@auth_required
def parse_improvement_recommendations_route():
    """
    Endpoint to parse improvement recommendations using file summaries.
    Expects JSON data with 'collection_name'.
    """
    try:
        data = request.get_json()
        if not data:
            return error_response(400, 'JSON data is required')
            
        collection_name = data.get('collection_name')
        if not collection_name:
            return error_response(400, 'collection_name is required')
        
        # Validate collection_name
        if not _validate_collection_name(collection_name):
            return error_response(400, 'Invalid collection name format')

        # Get summaries from database using helper
        summaries, filename, _ = _get_summaries_by_collection(collection_name)
        
        if not summaries:
            return error_response(404, 'File summaries not found')

        # Parse improvement recommendations using summaries
        recommendations, token_usage = powerbi_docs_service.parse_improvement_recommendations_from_summaries(summaries)
        
        # Save generated recommendations to database with graceful error handling
        try:
            # Store the recommendations in the same format as other sections
            recommendations_data = {
                'recommendations': recommendations,
                'count': len(recommendations)
            }
            generated_docs_service.save_generated_section(
                collection_name,
                'improvement_recommendations',
                recommendations_data
            )
        except Exception as save_error:
            # Log error but don't fail recommendation parsing
            logger.error(f"Failed to save improvement recommendations: {save_error}", exc_info=True)
        
        # Record token usage with graceful error handling
        try:
            user = get_current_user_from_token()
            if user and isinstance(user, dict) and user.get('ms_object_id'):
                powerbi_docs_token_tracking_service.record_token_usage(
                    user['ms_object_id'],
                    collection_name,
                    'improvement_recommendations',
                    token_usage.get('input_tokens', 0),
                    token_usage.get('output_tokens', 0)
                )
        except Exception as tracking_error:
            # Log error but don't fail recommendation parsing
            logger.error(f"Failed to record token usage for improvement recommendations: {tracking_error}", exc_info=True)
        
        return jsonify({
            'recommendations': recommendations,
            'count': len(recommendations),
            'filename': filename,
            'token_usage': token_usage
        })

    except Exception as e:
        logger.error(f"Error parsing recommendations: {e}", exc_info=True)
        return error_response(500, 'Failed to parse improvement recommendations')

@powerbi_docs_bp.route('/api/powerbi-docs/get-diagnostics-kpis/<collection_name>', methods=['GET'])
@cross_origin(supports_credentials=True)
@auth_required
def get_diagnostics_kpis(collection_name):
    """
    Endpoint to get diagnostic KPIs for a specific collection.
    """
    try:
        # Validate collection_name
        if not _validate_collection_name(collection_name):
            return error_response(400, 'Invalid collection name format')
        
        summaries, filename, _ = _get_summaries_by_collection(collection_name)
        
        if not summaries:
            return error_response(404, 'File summaries not found')
        
        # Calculate KPIs from summaries
        kpis = diagnostics_kpi_service.calculate_kpis(summaries)
        
        return jsonify({
            'collection_name': collection_name,
            'filename': filename,
            'kpis': kpis,
            'status': 'success'
        })
    
    except Exception as e:
        logger.error(f"Error calculating KPIs for {collection_name}: {e}", exc_info=True)
        return error_response(500, 'Failed to calculate diagnostic KPIs')
