from flask import request, jsonify, current_app
from flask_cors import cross_origin
import logging
import re
from typing import Dict, Optional, Tuple, Any
from datetime import datetime
from . import powerbi_docs_bp
from app.auth2.middleware import auth_required, get_current_user_from_token
from app.powerbi_docs.powerbi_service_pbix import PowerBIPbixService
from app.powerbi_docs.ai_client import ai_client
from app.powerbi_docs.services.token_tracking_service import powerbi_docs_token_tracking_service
from app.powerbi_docs.services.generated_docs_service import generated_docs_service
from app.powerbi_docs.services.diagnostics_kpi_service import diagnostics_kpi_service
from app.powerbi_docs.services.rewrite_service import rewrite_service
from app.core.responses import error_response
from app.core.database import get_db_cursor
from app.powerbi_chat.services.vector_store_service import vector_store_service
from app.services.token_limit_service import usage_limit_service

# Initialize the service with the proper AI client instance
powerbi_docs_service = PowerBIPbixService(ai_client)

# Configure logger
logger = logging.getLogger(__name__)

# Note: PDF formatting templates are now stored in frontend and sent with each request
# No backend storage needed - works with multiple instances

# Allowed section types
ALLOWED_SECTIONS = {
    'executive_summary',
    'data_model_analysis',
    'visualization_analysis',
    'security_analysis',
    'improvement_recommendations'
}

def _validate_collection_name(collection_name: str) -> bool:
    """
    Validate and sanitize collection_name to prevent SQL injection and path traversal.
    
    Collection names should be alphanumeric with underscores and hyphens only,
    matching the pattern used by vector_store_service (pbix_ prefix + hex UUID).
    
    Args:
        collection_name: The collection name to validate
        
    Returns:
        bool: True if valid, False otherwise
    """
    if not collection_name or not isinstance(collection_name, str):
        return False
    
    # Collection names should match pattern: pbix_ followed by hex characters
    # This matches the pattern generated by vector_store_service.generate_collection_name()
    pattern = r'^pbix_[a-f0-9]{32}$'
    return bool(re.match(pattern, collection_name))

def _get_summaries_by_collection(collection_name: str) -> Tuple[Optional[Dict], Optional[str], Optional[datetime]]:
    """
    Helper function to get summaries from database by collection name.
    
    Returns:
        tuple: (summaries_dict, filename, upload_time) or (None, None, None) if not found
    """
    try:
        with get_db_cursor(commit=False) as cursor:
            cursor.execute("""
                SELECT semantic_model_summary, power_query_summary, visuals_summary, rls_summary, filename, upload_time
                FROM powerbi_file_summaries 
                WHERE collection_name = %s
            """, (collection_name,))
            
            result = cursor.fetchone()
            
            if not result:
                return None, None, None
            
            semantic_model_summary, power_query_summary, visuals_summary, rls_summary, filename, upload_time = result
            
            summaries = {
                'semantic_model_summary': semantic_model_summary,
                'power_query_summary': power_query_summary,
                'visuals_summary': visuals_summary,
                'rls_summary': rls_summary or {}
            }
            
            return summaries, filename, upload_time
                
    except Exception as e:
        logger.error(f"Error retrieving summaries for {collection_name}: {e}", exc_info=True)
        raise


@powerbi_docs_bp.route('/api/powerbi-docs/list-files', methods=['GET'])
@cross_origin(supports_credentials=True)
@auth_required
def list_uploaded_files():
    """
    Endpoint to list all uploaded Power BI files.
    Returns the same format as the chat service.
    """
    try:
        uploaded_files = vector_store_service.list_collections_with_details()
        return jsonify({
            'files': uploaded_files,
            'total_count': len(uploaded_files),
            'status': 'success'
        })
    except Exception as e:
        logger.error(f"Error retrieving list of uploaded files: {e}", exc_info=True)
        return error_response(500, 'Failed to retrieve uploaded files.')

@powerbi_docs_bp.route('/api/powerbi-docs/get-summaries/<collection_name>', methods=['GET'])
@cross_origin(supports_credentials=True)
@auth_required
def get_file_summaries(collection_name):
    """
    Endpoint to get summaries for a specific collection.
    """
    try:
        # Validate collection_name
        if not _validate_collection_name(collection_name):
            return error_response(400, 'Invalid collection name format')
        
        summaries, filename, upload_time = _get_summaries_by_collection(collection_name)
        
        if not summaries:
            return error_response(404, 'File summaries not found')
        
        return jsonify({
            'collection_name': collection_name,
            'filename': filename,
            'upload_time': upload_time.isoformat() if upload_time else None,
            'summaries': summaries,
            'status': 'success'
        })

    except Exception as e:
        logger.error(f"Error retrieving summaries for {collection_name}: {e}", exc_info=True)
        return error_response(500, 'Failed to retrieve file summaries.')

@powerbi_docs_bp.route('/api/powerbi-docs/get-generated-docs/<collection_name>', methods=['GET'])
@cross_origin(supports_credentials=True)
@auth_required
def get_generated_docs(collection_name):
    """
    Endpoint to get all previously generated documentation sections for a collection.
    """
    try:
        # Validate collection_name
        if not _validate_collection_name(collection_name):
            return error_response(400, 'Invalid collection name format')
        
        generated_sections = generated_docs_service.get_all_generated_sections(collection_name)
        
        return jsonify({
            'collection_name': collection_name,
            'generated_sections': generated_sections,
            'status': 'success'
        })

    except Exception as e:
        logger.error(f"Error retrieving generated docs for {collection_name}: {e}", exc_info=True)
        return error_response(500, 'Failed to retrieve generated documentation.')


@powerbi_docs_bp.route('/api/powerbi-docs/analyze-section/<section>', methods=['POST'])
@cross_origin(supports_credentials=True)
@auth_required
def analyze_pbix_section_route(section):
    """
    Endpoint to analyze a specific section using file summaries.
    Accepts multipart/form-data with:
    - collection_name (required)
    - custom_instructions (optional)
    - pdf_file (optional) - PDF formatting template sent from frontend
    """
    try:
        # Validate section parameter
        if section not in ALLOWED_SECTIONS:
            return error_response(400, f'Invalid section. Allowed sections: {", ".join(sorted(ALLOWED_SECTIONS))}')
        
        # Handle both JSON and multipart/form-data requests
        if request.content_type and 'multipart/form-data' in request.content_type:
            collection_name = request.form.get('collection_name')
            custom_instructions = request.form.get('custom_instructions', '')
            pdf_file = request.files.get('pdf_file')
        else:
            # Legacy JSON support
            data = request.get_json()
            if not data:
                return error_response(400, 'Request data is required')
            collection_name = data.get('collection_name')
            custom_instructions = data.get('custom_instructions', '')
            pdf_file = None
            
        if not collection_name:
            return error_response(400, 'collection_name is required')
        
        # Validate collection_name
        if not _validate_collection_name(collection_name):
            return error_response(400, 'Invalid collection name format')
            
        if not isinstance(custom_instructions, str):
            custom_instructions = ''

        # Get summaries from database using helper
        summaries, filename, _ = _get_summaries_by_collection(collection_name)
        
        if not summaries:
            return error_response(404, 'File summaries not found')

        # Check usage limit before generating documentation
        warning_message = ''
        try:
            user = get_current_user_from_token()
            if user and isinstance(user, dict) and user.get('ms_object_id'):
                user_ms_object_id = user['ms_object_id']
                allowed, current_usage, limit, message = usage_limit_service.check_usage_limit(
                    user_ms_object_id,
                    feature_type='docs'
                )
                
                if not allowed:
                    return jsonify({
                        'error': 'usage_limit_exceeded',
                        'message': message,
                        'current_usage': {'count': current_usage},
                        'limit': {'count': limit},
                        'feature_type': 'docs'
                    }), 403
                
                # Check if approaching limit (only if limit not exceeded)
                try:
                    is_approaching, approaching_usage, approaching_limit, remaining, approaching_warning = usage_limit_service.check_approaching_limit(
                        user_ms_object_id,
                        feature_type='docs'
                    )
                    
                    if is_approaching:
                        warning_message = approaching_warning
                        logger.info(f"User {user_ms_object_id} is approaching docs limit. Remaining: {remaining}")
                except Exception as approaching_check_error:
                    # Log error but don't block request
                    logger.error(f"Error checking approaching limit: {approaching_check_error}", exc_info=True)
        except Exception as limit_check_error:
            # Log error but allow request to proceed (fail open)
            logger.error(f"Error checking usage limit: {limit_check_error}", exc_info=True)

        # Handle PDF file if provided (frontend sends it with each request)
        file_uri = None
        if pdf_file and pdf_file.filename:
            try:
                # Validate PDF file
                if not pdf_file.filename.lower().endswith('.pdf'):
                    logger.warning(f"Invalid file type for PDF formatting: {pdf_file.filename}")
                else:
                    # Check file size (20MB limit)
                    pdf_file.seek(0, 2)
                    file_size = pdf_file.tell()
                    pdf_file.seek(0)
                    
                    max_size = 20 * 1024 * 1024  # 20MB
                    if file_size <= max_size and file_size > 0:
                        # Save temporarily and upload to Gemini
                        import tempfile
                        import os
                        import google.generativeai as genai
                        from app.config.settings import config
                        import time
                        
                        temp_dir = os.path.join(current_app.instance_path, 'temp_uploads')
                        os.makedirs(temp_dir, exist_ok=True)
                        
                        temp_file = tempfile.NamedTemporaryFile(suffix='.pdf', dir=temp_dir, delete=False)
                        temp_filename = temp_file.name
                        
                        try:
                            pdf_file.save(temp_filename)
                            temp_file.close()
                            
                            # Upload to Gemini Files API
                            genai.configure(api_key=config.GOOGLE_API_KEY)
                            uploaded_file = genai.upload_file(
                                path=temp_filename,
                                display_name=pdf_file.filename
                            )
                            
                            # Wait for file to be processed
                            while uploaded_file.state.name == "PROCESSING":
                                time.sleep(2)
                                uploaded_file = genai.get_file(uploaded_file.name)
                            
                            if uploaded_file.state.name == "FAILED":
                                logger.warning(f"Failed to process PDF file with Gemini: {pdf_file.filename}")
                            else:
                                file_uri = uploaded_file.uri
                                logger.info(f"Uploaded PDF formatting template for collection {collection_name}: {pdf_file.filename}")
                        finally:
                            # Clean up temporary file
                            try:
                                if os.path.exists(temp_filename):
                                    os.remove(temp_filename)
                            except Exception as cleanup_error:
                                logger.warning(f"Failed to cleanup temp PDF file: {cleanup_error}")
            except Exception as pdf_error:
                logger.warning(f"Error processing PDF file: {pdf_error}. Continuing without PDF formatting.")

        # Analyze the specific section using summaries
        section_analysis, token_usage = powerbi_docs_service.analyze_from_summaries(
            summaries, 
            section, 
            custom_instructions,
            file_uri
        )
        
        # Log content length before saving
        analysis_length = len(str(section_analysis)) if section_analysis else 0
        logger.info(f"Section analysis complete for {section} - Length: {analysis_length} chars, preparing to save")
        
        # Save generated content to database with graceful error handling
        try:
            generated_docs_service.save_generated_section(
                collection_name,
                section,
                section_analysis
            )
        except Exception as save_error:
            # Log error but don't fail document generation
            logger.error(f"Failed to save generated section {section}: {save_error}", exc_info=True)
        
        # Record token usage with graceful error handling
        try:
            user = get_current_user_from_token()
            if user and isinstance(user, dict) and user.get('ms_object_id'):
                powerbi_docs_token_tracking_service.record_token_usage(
                    user['ms_object_id'],
                    collection_name,
                    section,
                    token_usage.get('input_tokens', 0),
                    token_usage.get('output_tokens', 0)
                )
        except Exception as tracking_error:
            # Log error but don't fail document generation
            logger.error(f"Failed to record token usage for section {section}: {tracking_error}", exc_info=True)
        
        response_data = {
            'section': section,
            'analysis': section_analysis,
            'custom_instructions': custom_instructions,
            'filename': filename,
            'token_usage': token_usage
        }
        
        # Include warning message if approaching limit
        if warning_message:
            response_data['warning'] = {
                'type': 'approaching_limit',
                'message': warning_message,
                'feature_type': 'docs'
            }
        
        return jsonify(response_data)

    except Exception as e:
        logger.error(f"Error analyzing section {section}: {e}", exc_info=True)
        return error_response(500, 'Failed to analyze section')

@powerbi_docs_bp.route('/api/powerbi-docs/parse-recommendations', methods=['POST'])
@cross_origin(supports_credentials=True)
@auth_required
def parse_improvement_recommendations_route():
    """
    Endpoint to parse improvement recommendations using file summaries.
    Expects JSON data with 'collection_name'.
    Note: PDF formatting is not used for improvement recommendations.
    """
    try:
        data = request.get_json()
        if not data:
            return error_response(400, 'JSON data is required')
            
        collection_name = data.get('collection_name')
        if not collection_name:
            return error_response(400, 'collection_name is required')
        
        # Validate collection_name
        if not _validate_collection_name(collection_name):
            return error_response(400, 'Invalid collection name format')

        # Get summaries from database using helper
        summaries, filename, _ = _get_summaries_by_collection(collection_name)
        
        if not summaries:
            return error_response(404, 'File summaries not found')

        # Parse improvement recommendations using summaries (no PDF formatting)
        recommendations, token_usage = powerbi_docs_service.parse_improvement_recommendations_from_summaries(summaries, None)
        
        # Save generated recommendations to database with graceful error handling
        try:
            # Store the recommendations in the same format as other sections
            recommendations_data = {
                'recommendations': recommendations,
                'count': len(recommendations)
            }
            generated_docs_service.save_generated_section(
                collection_name,
                'improvement_recommendations',
                recommendations_data
            )
        except Exception as save_error:
            # Log error but don't fail recommendation parsing
            logger.error(f"Failed to save improvement recommendations: {save_error}", exc_info=True)
        
        # Record token usage with graceful error handling
        try:
            user = get_current_user_from_token()
            if user and isinstance(user, dict) and user.get('ms_object_id'):
                powerbi_docs_token_tracking_service.record_token_usage(
                    user['ms_object_id'],
                    collection_name,
                    'improvement_recommendations',
                    token_usage.get('input_tokens', 0),
                    token_usage.get('output_tokens', 0)
                )
        except Exception as tracking_error:
            # Log error but don't fail recommendation parsing
            logger.error(f"Failed to record token usage for improvement recommendations: {tracking_error}", exc_info=True)
        
        return jsonify({
            'recommendations': recommendations,
            'count': len(recommendations),
            'filename': filename,
            'token_usage': token_usage
        })

    except Exception as e:
        logger.error(f"Error parsing recommendations: {e}", exc_info=True)
        return error_response(500, 'Failed to parse improvement recommendations')

@powerbi_docs_bp.route('/api/powerbi-docs/get-diagnostics-kpis/<collection_name>', methods=['GET'])
@cross_origin(supports_credentials=True)
@auth_required
def get_diagnostics_kpis(collection_name):
    """
    Endpoint to get diagnostic KPIs for a specific collection.
    """
    try:
        # Validate collection_name
        if not _validate_collection_name(collection_name):
            return error_response(400, 'Invalid collection name format')
        
        summaries, filename, _ = _get_summaries_by_collection(collection_name)
        
        if not summaries:
            return error_response(404, 'File summaries not found')
        
        # Calculate KPIs from summaries
        kpis = diagnostics_kpi_service.calculate_kpis(summaries)
        
        return jsonify({
            'collection_name': collection_name,
            'filename': filename,
            'kpis': kpis,
            'status': 'success'
        })
    
    except Exception as e:
        logger.error(f"Error calculating KPIs for {collection_name}: {e}", exc_info=True)
        return error_response(500, 'Failed to calculate diagnostic KPIs')

@powerbi_docs_bp.route('/api/powerbi-docs/get-diagnostics-kpi-details/<collection_name>/<kpi_type>', methods=['GET'])
@cross_origin(supports_credentials=True)
@auth_required
def get_diagnostics_kpi_details(collection_name, kpi_type):
    """
    Endpoint to get detailed items for a specific KPI type.
    
    Args:
        collection_name: The collection name
        kpi_type: One of 'unused_measures', 'unused_columns', 'inactive_relationships',
                  'large_tables', 'complex_measures', 'crowded_pages', 'many_to_many_relationships'
    """
    try:
        # Validate collection_name
        if not _validate_collection_name(collection_name):
            return error_response(400, 'Invalid collection name format')
        
        # Validate kpi_type
        valid_kpi_types = [
            'unused_measures', 
            'unused_columns', 
            'inactive_relationships',
            'large_tables',
            'complex_measures',
            'crowded_pages',
            'many_to_many_relationships'
        ]
        if kpi_type not in valid_kpi_types:
            return error_response(400, f'Invalid KPI type. Must be one of: {", ".join(valid_kpi_types)}')
        
        summaries, filename, _ = _get_summaries_by_collection(collection_name)
        
        if not summaries:
            return error_response(404, 'File summaries not found')
        
        # Calculate KPIs from summaries
        kpis = diagnostics_kpi_service.calculate_kpis(summaries)
        
        # Return only the requested KPI details
        kpi_data = kpis.get(kpi_type, {})
        
        return jsonify({
            'collection_name': collection_name,
            'filename': filename,
            'kpi_type': kpi_type,
            'details': kpi_data.get('items', []),
            'count': kpi_data.get('count', 0),
            'status': 'success'
        })
    
    except Exception as e:
        logger.error(f"Error getting KPI details for {collection_name}/{kpi_type}: {e}", exc_info=True)
        return error_response(500, 'Failed to get KPI details')

@powerbi_docs_bp.route('/api/powerbi-docs/rewrite-section', methods=['POST'])
@cross_origin(supports_credentials=True)
@auth_required
def rewrite_section():
    """
    Endpoint to rewrite a specific portion of a documentation section.
    Expects JSON data with 'collection_name', 'section_name', 'selected_text', 
    'start_position', 'end_position', and 'rewrite_style'.
    """
    try:
        data = request.get_json()
        if not data:
            return error_response(400, 'JSON data is required')
        
        collection_name = data.get('collection_name')
        if not collection_name:
            return error_response(400, 'collection_name is required')
        
        # Validate collection_name
        if not _validate_collection_name(collection_name):
            return error_response(400, 'Invalid collection name format')
        
        section_name = data.get('section_name')
        if not section_name:
            return error_response(400, 'section_name is required')
        
        # Validate section_name
        if section_name not in ALLOWED_SECTIONS:
            return error_response(400, f'Invalid section. Allowed sections: {", ".join(sorted(ALLOWED_SECTIONS))}')
        
        selected_text = data.get('selected_text')
        if not selected_text or not isinstance(selected_text, str):
            return error_response(400, 'selected_text is required and must be a string')
        
        start_position = data.get('start_position')
        end_position = data.get('end_position')
        
        if start_position is None or end_position is None:
            return error_response(400, 'start_position and end_position are required')
        
        try:
            start_position = int(start_position)
            end_position = int(end_position)
        except (ValueError, TypeError):
            return error_response(400, 'start_position and end_position must be integers')
        
        rewrite_style = data.get('rewrite_style')
        if not rewrite_style or rewrite_style not in ['concise', 'professional', 'casual']:
            return error_response(400, 'rewrite_style is required and must be one of: concise, professional, casual')
        
        # Get current section to verify it exists
        section_data = generated_docs_service.get_generated_section(collection_name, section_name)
        if not section_data:
            return error_response(404, 'Section not found')
        
        # Rewrite the selected text using AI
        try:
            rewritten_text, token_usage = rewrite_service.rewrite_text_selection(selected_text, rewrite_style)
        except Exception as rewrite_error:
            logger.error(f"Error rewriting text: {rewrite_error}", exc_info=True)
            return error_response(500, f'Failed to rewrite text: {str(rewrite_error)}')
        
        # Update the section with the rewritten text at the specified positions
        try:
            updated_content = generated_docs_service.update_section_by_positions(
                collection_name,
                section_name,
                start_position,
                end_position,
                rewritten_text
            )
            
            if not updated_content:
                return error_response(500, 'Failed to update section')
        except Exception as update_error:
            logger.error(f"Error updating section: {update_error}", exc_info=True)
            return error_response(500, f'Failed to update section: {str(update_error)}')
        
        # Record token usage with graceful error handling
        try:
            user = get_current_user_from_token()
            if user and isinstance(user, dict) and user.get('ms_object_id'):
                powerbi_docs_token_tracking_service.record_token_usage(
                    user['ms_object_id'],
                    collection_name,
                    f'{section_name}_rewrite',
                    token_usage.get('input_tokens', 0),
                    token_usage.get('output_tokens', 0)
                )
        except Exception as tracking_error:
            # Log error but don't fail the rewrite operation
            logger.error(f"Failed to record token usage for rewrite: {tracking_error}", exc_info=True)
        
        return jsonify({
            'section': section_name,
            'updated_content': updated_content,
            'rewrite_style': rewrite_style,
            'token_usage': token_usage,
            'status': 'success'
        })
    
    except Exception as e:
        logger.error(f"Error rewriting section: {e}", exc_info=True)
        return error_response(500, 'Failed to rewrite section')

# Note: PDF formatting endpoints (upload/remove/get) have been removed.
# PDFs are now stored in frontend and sent with each generation request.
# See FRONTEND_PDF_STORAGE.md for implementation details.